import type { LucideIcon } from 'lucide-react';
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Bell,
  Building2,
  Calendar,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Clock,
  Copy,
  Eye,
  EyeOff,
  FileText,
  History,
  Image,
  Info,
  Key,
  Lock,
  LogIn,
  LogOut,
  MapPin,
  MessageSquare,
  PanelLeft,
  Pencil,
  Plus,
  RefreshCw,
  Repeat,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  SquareCheck,
  Store,
  Trash2,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserPlus,
  Users,
  X,
} from 'lucide-react';

/** Nomes legados (Tabler) mapeados para ícones Lucide — mesma biblioteca do Psico Lume. */
export const iconRegistry = {
  adjustments: SlidersHorizontal,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  badge: BadgeCheck,
  bell: Bell,
  building: Building2,
  'building-store': Store,
  calendar: Calendar,
  'calendar-event': CalendarDays,
  check: Check,
  checkbox: SquareCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  clock: Clock,
  copy: Copy,
  eye: Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  history: History,
  'info-circle': Info,
  key: Key,
  'layout-sidebar': PanelLeft,
  lock: Lock,
  login: LogIn,
  logout: LogOut,
  'map-pin': MapPin,
  message: MessageSquare,
  pencil: Pencil,
  photo: Image,
  plus: Plus,
  refresh: RefreshCw,
  repeat: Repeat,
  search: Search,
  selector: ChevronsUpDown,
  settings: Settings,
  'shield-lock': ShieldCheck,
  trash: Trash2,
  upload: Upload,
  user: User,
  'user-check': UserCheck,
  'user-cog': UserCog,
  'user-plus': UserPlus,
  users: Users,
  x: X,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;

export function isIconName(name: string): name is IconName {
  return name in iconRegistry;
}
